### PR TITLE
Browser Independent version of Extension

### PR DESCRIPTION
**Pull request by keif888**
This pull request allows the extension to be loaded into Chrome, Edge and FireFox.
This addresses issue #2 Firefox Extension.

FireFox changes the permission handling such that the end user has to approve each PhotoPrism site that they want it to run on.

That change is explained when the Extension is installed via the Install.html, which shows on install or upgrade (as shown below).
image

The Popup now asks to Grant Access.
Screenshot 2024-09-11 180747

And after Granting Access, you will get a browser prompt like:
Screenshot 2024-09-11 180802

And the browser will then refresh as the extension installs.

If you want to revoke access, the popup allows that:
image

Revoke can also be done from the Options tab.  Although that is much harder to find in FireFox.
image

Also added is the ability to hide the map when editing photo by photo if the user desires.
This is the Hidden size, which can be set from the Popup or the Options page.
image

I have NOT tested an upgrade from the current version to the new version as I can't package it.
I have tested this on Windows 11 
- Chrome 128.0.6613.120
- FireFox 130.0
- Edge 128.0.2739.67
And Debian 12.7 (I didn't capture the version numbers)
- Chrome 
- FireFox

### CODE REVIEW

**Comment by keif888** [comment]
How it all works:

**manifest.json** now has optional_host_permissions that allow the user to authorise it to run on sites.  It no longer has the content script and matches, as these are done dynamically via the popup invocation.

**worker.js** now does a lot more.  

- It shows a new install.html on the installation or upgrade of the extension via chrome.runtime.onInstalled.addListener
- It stores the tabid passed via messages from the popup via chrome.runtime.onMessage.addListener so the worker can interact with the tab.  Had to do it this way due to the popup closing before completion in some cases.
- When the permissions are added (via the popup) they are caught by chrome.permissions.onAdded.addListener.  That gets the cached tabid then removes the cached information, and fires registerMatchAndScript with a second delay
- function injectContentScript injects the contentScript.js into a tab, so long as it is not already there.  Sometimes the browser doesn't match and auto inject the content script on landing on a page (when you start at library/albums for example), and this fixes those cases
- function registerMatchAndScript registers the content script and match information so long as the script is not already on the tab
- When any tab in the browser is updated chrome.tabs.onUpdated.addListener fires and if the update is complete AND the extension has permissions on the tab then it will fire injectContentScript

**install.html** shows the welcome and usage message, allows the change of image size, lists all the approved sites and allows the user to revoke sites

**options.html** allows the change of image size, lists all the approved sites and allows the user to revoke sites

**popup.html** allows the change of image size, lists all the approved sites and allows the user to approve or revoke depending on state) the page that was active when they clicked on the extension

**sharedoptions.js** is used by all the html files to validate and save the size options and check if a URL is valid

**options.js** is used by install.html and options.html.  It supports:

- restore_options to get the saved size, and call the function to build the list of approved sites
- revoke_permissions to remove the registered content script and match and the permissions for each checked site in the table
- buildCheckboxList creates a table with a check boxed row for each site that has been approved and adds it to the html page
- 3 listeners

**popup.js** is used by popup.html.  It supports:

- restore_options to get the saved size, save tabid, pass it to worker.js (which has a listener for messages), enable/disable buttons and call the function to build the list of approved sites
- grant_permissions **SYNC** function to request the user to approve the permission request.  This MUST by SYNC in FireFox or it just doesn't work.  (worker.js has a listener for the changed permissions)
- revoke_permissions to remove the registered content script and match and the permissions for the site that the user is on when they clicked on the extension, and tell the source tab that it is revoked with a message
- buildTableHTML creates a table with a row for each site that has been approved and adds it to the html page
- 4 listeners

**contentScript.js** has few changes.  There is a new listener for messages listenerScriptLoaded which is used to stop the timers from running or let the caller know that it's here.

From the previous changes in the other pulls, the updatePhoto function was changed to:
- be able to check that the Geo Coordinates were changed as expected on success.  Retry up to 5 times if they were not.
- be able to retry up to 5 times if the update fails with a http 500.


The Debian 12.7 testing was against:
Chrome 128.0.6613.137 - Works
Firefox 130.0 - Works
I just tested against Firefox 115.15.0esr which fails as it doesn't understand [optional_host_permissions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/optional_host_permissions) as it came in Firefox 128.0

**manifest.json** may need to have the following changed
```
    "browser_specific_settings":{
        "gecko": {
            "id": "{edb79849-9fe0-48fe-afcf-46f4eabf6339}",
           "strict_min_version": "128.0"
        }
    }
```

**Comment by andyvalerio** [comment]
This is an incredible contribution. It makes the extension usable for a lot more people and gives it a more modern and professional touch with the possibility to revoke access for specific URLs. 

On behalf of all current and future users, thanks a lot Keith! ♥️

**Comment by EarthBoundX5** [comment]
Excellent timing, was just checking back to see issue #2 status and see this fantastic change!

> This is an incredible contribution. It makes the extension usable for a lot more people and gives it a more modern and professional touch with the possibility to revoke access for specific URLs.
> 
> On behalf of all current and future users, thanks a lot Keith! ♥️

Any appetite for submitting and getting it signed for use with Firefox now?  Unless there is a different I'm not aware of to get unsigned add-ons into the main / standard / rapid release versions of Firefox?

https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview/

**Comment by andyvalerio** [comment]
> Excellent timing, was just checking back to see issue #2 status and see this fantastic change!
> 
> > This is an incredible contribution. It makes the extension usable for a lot more people and gives it a more modern and professional touch with the possibility to revoke access for specific URLs.
> > On behalf of all current and future users, thanks a lot Keith! ♥️
> 
> Any appetite for submitting and getting it signed for use with Firefox now? Unless there is a different I'm not aware of to get unsigned add-ons into the main / standard / rapid release versions of Firefox?
> 
> https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview/

Hi! 
I don't have an ambition to do that, at the moment. I'm happy the extension can be used on different browsers but I don't really have the time to maintain several release tracks in parallel. 🙈

**Pull request merged**
